### ISSUE TITLE
Need to add codecov token to project secrets

### ISSUE THREAD

**Issue by l3r8yJ** [objectionary/sodg#179]
we're got an error on `master` branch:

```
error - 2024-12-01 13:32:00,889 -- Commit creating failed: {"message":"Token required because branch is protected"}
```
It would be fixed by editing `.github/workflows/tarpaulin.yml` like that:
```yaml
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
```

@yegor256 take a look, please, only you can set a codecov token
